//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.LoadWolves = new HashSet<LoadWolf>();
            this.Invites = new HashSet<Invite>();
            this.VIPs = new HashSet<VIP>();
        }
    
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Wolves { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<LoadWolf> LoadWolves { get; set; }
        public virtual ICollection<Invite> Invites { get; set; }
        public virtual ICollection<VIP> VIPs { get; set; }
    }
}
